### PR TITLE
Implement download buttons for admin approval of NOK proof

### LINKED ISSUE #44: [$50] The proof Download button is not working
## Target URL

https://frontend.app.cloud.gov/admin/setting

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Login as a valid User [Admin]
3. Click Search button
4. Enter 'Branch of service' as US NAVY
5. Click 'Update Results' button
6. Click on any record > https://frontend.app.cloud.gov/dashboard/10
7. Click on 'Send NOK Request' button
8. Enter all the required details and submit
9. Click on Username and go to profile page
10. Click NOK Request > For Review
11. Click Download

## Actual Result(s)

- The proof Download button is not working

## Expected Result(s)

- Must download the file

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 67.0.3396.87 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by ramillim**
Fixes #44 

Same implementation as PR #73, but for the admin menu

image

### CODE REVIEW

**Comment by dustinWeaver** [comment]
@ramillim, I can't see to get this to work on https://frontend.app.cloud.gov/.  Would it be related to the file storage?  Basically I get no error message or anything when I click the button.

Currently I can't view the logs.

**Comment by dustinWeaver** [comment]
More info, here's the logs:

> 2018-06-28T11:31:29.04-0500 [APP/PROC/WEB/0] OUT [Thu Jun 28 2018 16:31:29 GMT+0000 (UTC)] "GET /upload/15ab0bce9f20ae7aa5d0e325fdcf2c4e" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
   2018-06-28T11:31:29.04-0500 [RTR/0] OUT frontend.app.cloud.gov - [2018-06-28T16:31:29.041+0000] "GET /upload/15ab0bce9f20ae7aa5d0e325fdcf2c4e HTTP/1.1" 404 0 0 "https://frontend.app.cloud.gov/admin/setting" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36" "127.0.0.1:32668" "10.10.2.9:63419" x_forwarded_for:"204.156.181.151, 127.0.0.1" x_forwarded_proto:"https" vcap_request_id:"829c1ef6-81b3-44a2-7122-4d0937a878d3" response_time:0.004083953 app_id:"37c72dd0-3592-4604-a6f8-b0f02ed5fda7" app_index:"0" x_b3_traceid:"c6ee319bf3d517ff" x_b3_spanid:"c6ee319bf3d517ff" x_b3_parentspanid:"-"
   2018-06-28T11:31:29.04-0500 [RTR/0] OUT
   2018-06-28T11:31:29.04-0500 [APP/PROC/WEB/0] OUT [Thu Jun 28 2018 16:31:29 GMT+0000 (UTC)] "GET /upload/15ab0bce9f20ae7aa5d0e325fdcf2c4e" Error (404): "Not found"

Does appear related to the upload space.

**Comment by ramillim** [comment]
@dustinWeaver  I suspect it's an old NOK request that was created on a previous server, but the database was re-used. I do notice that the download button is not properly displaying an error that the resource cannot be found, so I will get you that fix by tomorrow.

I was trying to create a new NOK request so we could see if that new one was downloadable, but there's also an issue with submitting a new NOK responds with a server-side validation error on the email field. I'll investigate that as well.

**Comment by ramillim** [comment]
@dustinWeaver This PR gives better feedback to the user about why clicking on the link failed https://github.com/topcoderinc/va-online-memorial-frontend/pull/75

Also fixed the bug I mentioned about not being able to submit the form for new NOK requests.

**Pull request merged**
